name: 'deploy with pulumi'
description: 'deploy IaC stack with Pulumi'
inputs:
  tag:
    description: 'image tag'
    required: false
    default: ${{ github.sha }}
  node:
    description: 'nodejs version'
    required: false
    default: '20'
  workdir:
    description: 'root directory for Pulumi files'
    required: false
    default: '.IaC'
  command:
    description: 'pulumi command'
    required: false
    default: 'up'
  stack:
    description: 'pulumi stack'
    required: true
  token:
    description: 'pulumi access token'
    required: true
runs:
  using: "composite"
  steps:
  - name: checkout repository
    uses: actions/checkout@v4
  - name: setup node
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node }}
  - name: restore pulumi dependencies cache
    uses: actions/cache/restore@v4
    id: pulumi-cache
    with:
      key: pulumi.cache.${{ hashFiles(format('{0}/package-lock.json', inputs.workdir)) }}
      path: ${{ format('{0}/node_modules', inputs.workdir) }}
  - name: install dependencies for pulumi
    run: npm ci
    shell: sh
    if: steps.pulumi-cache.outputs.cache-hit != 'true'
    working-directory: ${{ inputs.workdir }}
  - name: update resources in the pulumi stack
    uses: pulumi/actions@v5
    with:
      command: ${{ inputs.command }}
      stack-name: ${{ inputs.stack }}
      work-dir: ${{ inputs.workdir }}
    env:
      STACK: ${{ inputs.stack }}
      IMAGE_TAG: ${{ inputs.tag }}
      PULUMI_ACCESS_TOKEN: ${{ inputs.token }}
  - name: save pulumi dependencies cache
    uses: actions/cache/save@v4
    if: steps.pulumi-cache.outputs.cache-hit != 'true'
    with:
      key: pulumi.cache.${{ hashFiles(format('{0}/package-lock.json', inputs.workdir)) }}
      path: ${{ format('{0}/node_modules', inputs.workdir) }}
