name: 'deploy with pulumi'
description: 'deploy IaC stack with Pulumi'
inputs:
  tag:
    description: 'image tag'
    required: false
    default: ${{ github.sha }}
  node:
    description: 'nodejs version'
    required: false
    default: '22.x'
  workdir:
    description: 'root directory for Pulumi files'
    required: false
    default: '.IaC'
  command:
    description: 'pulumi command'
    required: false
    default: 'up'
  stack:
    description: 'pulumi stack'
    required: true
  token:
    description: 'pulumi access token'
    required: true
runs:
  using: "composite"
  steps:
  - name: checkout repository
    uses: actions/checkout@v4
  - name: setup node
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node }}
  - name: install pnpm
    uses: pnpm/action-setup@v3
    with:
      version: latest
      run_install: false
  - name: get pnpm store directory
    shell: sh
    run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
  - uses: actions/cache@v4
    name: setup pnpm cache
    with:
      path: ${{ env.STORE_PATH }}
      key: pulumi.cache.${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.workdir)) }}
      restore-keys: |
        pulumi.cache.
  - name: install dependencies for pulumi
    run: pnpm install
    shell: sh
    if: steps.pulumi-cache.outputs.cache-hit != 'true'
    working-directory: ${{ inputs.workdir }}
  - name: update resources in the pulumi stack
    uses: pulumi/actions@v5
    with:
      command: ${{ inputs.command }}
      stack-name: ${{ inputs.stack }}
      work-dir: ${{ inputs.workdir }}
    env:
      STACK: ${{ inputs.stack }}
      IMAGE_TAG: ${{ inputs.tag }}
      PULUMI_ACCESS_TOKEN: ${{ inputs.token }}
